pipeline {
    agent any
    tools {
        nodejs "my-nodejs"
    }
    stages {
        stage("install dependencies"){
            steps {
                dir('app') {
                    sh 'npm install'
                }
            }
        }
        stage('increment version'){
            when {
            expression {
              return env.GIT_BRANCH == "origin/main"
            }
          }

            steps{
                script {
                     echo 'Increment app version....'
                dir('app') {
                      // increment the minor version (ex: 1.0.0 -> 1.1.0)
                    sh 'npm version minor --no-git-tag-version'

                // read the new version 
                    def version = sh(script: "node -p \"require('./package.json').version\"", returnStdout: true).trim()

                    env.IMAGE_NAME = "${version}-${BUILD_NUMBER}"

                    echo "✅ new app version: ${env.IMAGE_NAME}"
                }

                }
               
                
            }
        }
        stage('run tests') {
            steps {
                dir('app'){
                    sh 'npm test || echo " tests not found..."'
                }
            }
        }
        
        stage('Build and push Docker image') {
            when {
            expression {
              return env.GIT_BRANCH == "origin/main"
            }
          }

            steps {
                echo 'pushing docker image to docker hub...'
                withCredentials([usernamePassword(credentialsId: 'nexus-docker-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "docker build -t 64.226.119.94:8083/nodejs-app-image:$IMAGE_NAME ./app"
                    sh 'echo $PASS | docker login -u $USER --password-stdin 64.226.119.94:8083'
                    sh "docker push 64.226.119.94:8083/nodejs-app-image:$IMAGE_NAME"
                }
  
            }
            
        }

        stage('deploy') {
            when {
            expression {
              return env.GIT_BRANCH == "origin/main"
            }
          }

            steps {
                script {
                     echo "Deploying application to EC2...."
                    def shellCmd = "bash ./server-cmds.sh 64.226.119.94:8083/nodejs-app-image:$IMAGE_NAME"
                    def ec2Instance = "ec2-user@3.120.189.189"
                    sshagent(['ec2-server-key']) {
                        sh "scp -o StrictHostKeyChecking=no server-cmds.sh ${ec2Instance}:/home/ec2-user"
                        sh "scp -o StrictHostKeyChecking=no docker-compose.yaml ${ec2Instance}:/home/ec2-user"
                        sh "ssh -o StrictHostKeyChecking=no ${ec2Instance} ${shellCmd}"
                    }
                }
            }
        }

        stage('commit version to Github') {
            when {
            expression {
              return env.GIT_BRANCH == "origin/main"
            }
          }

            steps {
                script {
                    echo 'commit version to github...'
                    script {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-credentials-push',
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )]) {

                        sh 'git config --global user.email "jenkins@example.com"'
            sh 'git config --global user.name "jenkins"'

            sh 'git remote -v'
            sh 'git status'
            sh 'git branch'
            sh 'git config --list'
            
            sh "git remote set-url origin https://${USER}:${PASS}@github.com/leonnelzanguim/jenkins-exercises.git"
            sh 'git add .'
            sh 'git commit -m "ci: version bump"'
            sh 'git push origin HEAD:main'

                    }

                }
            }
        }
    }
    }
}